name: Weekly Estate Sales Scraper

on:
  schedule:
    # Run every Monday at 8:00 AM Central Time (13:00 UTC)
    - cron: '0 13 * * 1'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
        
    - name: Run estate sales scraper
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python scrape_sales.py
